// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ExJdH3FMPRw3lTCfeevuEUnE6Js4jf4',
    appId: '1:104783052197:web:6285289a0b3130f56d3c4c',
    messagingSenderId: '104783052197',
    projectId: 'flutter-test-dist',
    authDomain: 'flutter-test-dist.firebaseapp.com',
    storageBucket: 'flutter-test-dist.firebasestorage.app',
    measurementId: 'G-R11N5CCY5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOqEwtNDFuKy8gxZrEjx-SZgNEtSS59k',
    appId: '1:104783052197:android:0f4dc3f4cb6473d86d3c4c',
    messagingSenderId: '104783052197',
    projectId: 'flutter-test-dist',
    storageBucket: 'flutter-test-dist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtUrku_vNcP0VHf8TevTbFEwX__SIEzA',
    appId: '1:104783052197:ios:db14828ac16cafe96d3c4c',
    messagingSenderId: '104783052197',
    projectId: 'flutter-test-dist',
    storageBucket: 'flutter-test-dist.firebasestorage.app',
    iosBundleId: 'com.example.myAppppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtUrku_vNcP0VHf8TevTbFEwX__SIEzA',
    appId: '1:104783052197:ios:db14828ac16cafe96d3c4c',
    messagingSenderId: '104783052197',
    projectId: 'flutter-test-dist',
    storageBucket: 'flutter-test-dist.firebasestorage.app',
    iosBundleId: 'com.example.myAppppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ExJdH3FMPRw3lTCfeevuEUnE6Js4jf4',
    appId: '1:104783052197:web:34bad0d2118f80666d3c4c',
    messagingSenderId: '104783052197',
    projectId: 'flutter-test-dist',
    authDomain: 'flutter-test-dist.firebaseapp.com',
    storageBucket: 'flutter-test-dist.firebasestorage.app',
    measurementId: 'G-X2JE0G6MJN',
  );
}
